// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN // defines main() automatically
#include "catch.hpp"
#include "A65.hpp"

// tests for exercise 1
TEST_CASE("Test1 ", "[Swap two values]")
{
	int n1, n2, n3;
	n1 = 10;
	n2 = 20;
	n3 = 30;
	swap(n1, n2);
	REQUIRE(n2 == 10);
	REQUIRE(n1 == 20);
	swap(n2, n3);
	REQUIRE(n3 == 10);
	REQUIRE(n2 == 30);
}
TEST_CASE("Test2 ", "[Swap three values]")
{
	int n1, n2, n3;
	n1 = 10;
	n2 = 20;
	n3 = 30;
	swap(n1, n2, n3);
	REQUIRE(n1 == 30);
	REQUIRE(n2 == 10);
	REQUIRE(n3 == 20);
}